services:
  frontend:
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
  backend:
    volumes:
      - ./backend:/code
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
