name: Docker CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: secrets.CR_PAT != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ secrets.CR_PAT != '' }}
          tags: ghcr.io/${{ github.repository_owner }}/thecove:latest
      - name: Tests
        run: |
          pip install -r backend/requirements.txt pytest
          pytest backend/tests -q
